# Generated by Django 4.2.16 on 2025-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_phone_verified_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', help_text='رقم الهاتف مطلوب', max_length=20),
            preserve_default=False,
        ),
    ]
