# Generated by Django 4.2.16 on 2025-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('pet_owner', 'مالك حيوان أليف'), ('clinic_staff', 'طاقم عيادة')], default='pet_owner', max_length=30),
        ),
    ]
