# Generated by Django 4.2.16 on 2025-10-17 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.ImageField(help_text='صورة بطاقة الهوية', upload_to='verification_documents/id_photos/', verbose_name='صورة الهوية')),
                ('selfie_video', models.FileField(blank=True, help_text='فيديو سيلفي مع الهوية (10-15 ثانية)', null=True, upload_to='verification_documents/selfie_videos/', verbose_name='فيديو السيلفي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات المشرف', null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب التحقق من الحساب',
                'verbose_name_plural': 'طلبات التحقق من الحسابات',
                'ordering': ['-created_at'],
            },
        ),
    ]
