# Generated by Django 4.2.16 on 2025-10-17 01:28

from django.db import migrations


def sync_user_verification_status(apps, schema_editor):
    AccountVerification = apps.get_model('accounts', 'AccountVerification')
    User = apps.get_model('accounts', 'User')

    approved_user_ids = set(
        AccountVerification.objects.filter(status='approved').values_list('user_id', flat=True)
    )

    if approved_user_ids:
        User.objects.filter(pk__in=approved_user_ids).update(is_verified=True)

    User.objects.filter(is_verified=True).exclude(pk__in=approved_user_ids).update(is_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountverification'),
    ]

    operations = [
        migrations.RunPython(sync_user_verification_status, migrations.RunPython.noop),
    ]
