# Generated by Django 4.2.16 on 2025-10-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sync_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_adoption_pets',
            field=models.BooleanField(default=True, help_text='إرسال إشعارات الحيوانات المتاحة للتبني'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_breeding_requests',
            field=models.BooleanField(default=True, help_text='إرسال إشعارات طلبات التزاوج'),
        ),
    ]
