# Generated by Django 4.2.16 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_notify_adoption_pets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('clinic_home_enabled', models.BooleanField(default=True)),
                ('clinic_map_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات تطبيق الموبايل',
                'verbose_name_plural': 'إعدادات تطبيق الموبايل',
            },
        ),
    ]
