# Generated by Django 4.2.17 on 2026-02-20

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mobile_app_config'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AddField(
            model_name='user',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                spatial_index=True,
                srid=4326,
            ),
        ),
    ]
