# Generated by Django 4.2.17 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_location_point_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappconfig',
            name='server_map_clustering_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
