# Generated by Django 4.2.17 on 2026-02-20

from django.db import migrations, models


def enable_server_map_clustering(apps, schema_editor):
    MobileAppConfig = apps.get_model('accounts', 'MobileAppConfig')
    updated = MobileAppConfig.objects.update(server_map_clustering_enabled=True)
    if updated == 0:
        MobileAppConfig.objects.create(
            key='default',
            clinic_home_enabled=True,
            clinic_map_enabled=True,
            server_map_clustering_enabled=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mobileappconfig_server_map_clustering_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappconfig',
            name='server_map_clustering_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_server_map_clustering, migrations.RunPython.noop),
    ]

