# Generated by Django 4.2.17 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usernotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappconfig',
            name='android_min_supported_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='android_recommended_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='android_store_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='ios_min_supported_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='ios_recommended_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='ios_store_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
