# Generated by Django 4.2.16 on 2025-08-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_hours', models.TextField(help_text='ساعات العمل')),
                ('services', models.TextField(help_text='الخدمات المتاحة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عيادة بيطرية',
                'verbose_name_plural': 'العيادات البيطرية',
            },
        ),
        migrations.CreateModel(
            name='VeterinaryCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('health', 'شهادة صحية'), ('vaccination', 'شهادة تطعيم'), ('breeding', 'شهادة صالح للتزاوج'), ('sterilization', 'شهادة تعقيم')], max_length=20)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(help_text='تفاصيل الشهادة')),
                ('veterinarian_name', models.CharField(help_text='اسم الطبيب البيطري', max_length=200)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='clinics.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pets.pet')),
            ],
            options={
                'verbose_name': 'شهادة بيطرية',
                'verbose_name_plural': 'الشهادات البيطرية',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('checkup', 'فحص دوري'), ('vaccination', 'تطعيم'), ('breeding_consultation', 'استشارة تزاوج'), ('pregnancy_check', 'فحص حمل'), ('emergency', 'طوارئ'), ('other', 'أخرى')], default='checkup', max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('reason', models.TextField(help_text='سبب الزيارة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('completed', 'تم'), ('cancelled', 'ملغي'), ('rescheduled', 'تم إعادة الجدولة')], default='scheduled', max_length=20)),
                ('diagnosis', models.TextField(blank=True, help_text='التشخيص', null=True)),
                ('treatment', models.TextField(blank=True, help_text='العلاج الموصى به', null=True)),
                ('next_appointment', models.DateField(blank=True, help_text='الموعد القادم', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='pets.pet')),
            ],
            options={
                'verbose_name': 'موعد بيطري',
                'verbose_name_plural': 'المواعيد البيطرية',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
