# Generated by Django 4.2.16 on 2025-09-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name'], 'verbose_name': 'عيادة بيطرية', 'verbose_name_plural': 'العيادات البيطرية'},
        ),
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, help_text='نبذة عن العيادة', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/logos/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='صاحب الحساب الرئيسي للعيادة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veterinaryappointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('pending', 'قيد المعالجة'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='veterinaryappointment',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='veterinaryappointment',
            name='appointment_type',
            field=models.CharField(choices=[('checkup', 'فحص دوري'), ('vaccination', 'تطعيم'), ('breeding_consultation', 'استشارة تزاوج'), ('pregnancy_check', 'فحص حمل'), ('emergency', 'طوارئ'), ('grooming', 'تنظيف وتجميل'), ('surgery', 'جراحة'), ('other', 'أخرى')], default='checkup', max_length=30),
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'فحص عام'), ('vaccination', 'تطعيم'), ('surgery', 'جراحة'), ('grooming', 'تنظيف وتجميل'), ('breeding', 'استشارات تزاوج'), ('boarding', 'إقامة ورعاية'), ('emergency', 'طوارئ'), ('other', 'خدمات أخرى')], default='general', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('highlight', models.BooleanField(default=False, help_text='إبراز الخدمة في الواجهة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_list', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'خدمة طبية',
                'verbose_name_plural': 'الخدمات الطبية',
                'ordering': ['clinic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('promotion_type', models.CharField(choices=[('discount', 'خصم مباشر'), ('bundle', 'باقة مركبة'), ('event', 'فعالية خاصة'), ('other', 'عروض أخرى')], default='discount', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'عرض عيادة',
                'verbose_name_plural': 'عروض العيادات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المتابعة'), ('resolved', 'تم الحل'), ('archived', 'مؤرشف')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'طارئ')], default='normal', max_length=10)),
                ('is_internal', models.BooleanField(default=False, help_text='رسالة داخلية لفريق العيادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'رسالة عيادة',
                'verbose_name_plural': 'رسائل العيادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالك العيادة'), ('veterinarian', 'طبيب بيطري'), ('assistant', 'مساعد طبي'), ('reception', 'استقبال'), ('admin', 'إداري')], default='owner', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='هل هو صاحب الحساب الرئيسي؟')),
                ('invitation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='clinics.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو فريق العيادة',
                'verbose_name_plural': 'أعضاء فريق العيادة',
                'unique_together': {('user', 'clinic')},
            },
        ),
    ]
