# Generated by Django 4.2.16 on 2025-10-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_options_clinic_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicClientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_records', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'عميل عيادة',
                'verbose_name_plural': 'عملاء العيادة',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicPatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=60)),
                ('breed', models.CharField(blank=True, max_length=120, null=True)),
                ('age_text', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('boarding', 'إقامة/ملاحظة')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='clinics.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinics.clinicclientrecord')),
            ],
            options={
                'verbose_name': 'مريض عيادة',
                'verbose_name_plural': 'مرضى العيادة',
                'ordering': ['name'],
            },
        ),
    ]
