# Generated by Django 4.2.16 on 2025-10-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0003_clinicclientrecord_clinicpatientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpatientrecord',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='المستخدم المرتبط بالحيوان في التطبيق', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_patient_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClinicInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تم القبول'), ('declined', 'تم الرفض'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20)),
                ('sms_send_count', models.PositiveIntegerField(default=0)),
                ('last_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clinics.clinic')),
                ('owner_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clinics.clinicclientrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clinics.clinicpatientrecord')),
                ('recipient', models.ForeignKey(blank=True, help_text='المستخدم الذي استلم الدعوة بعد التسجيل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دعوة عيادة',
                'verbose_name_plural': 'دعوات العيادات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='clinics_cli_token_78485e_idx'), models.Index(fields=['status', 'phone'], name='clinics_cli_status_10720b_idx'), models.Index(fields=['status', 'email'], name='clinics_cli_status_947035_idx')],
            },
        ),
    ]
