# Generated by Django 4.2.16 on 2025-10-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinicpatientrecord_linked_user_clinicinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpatientrecord',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
