# Generated by Django 4.2.17 on 2025-10-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinicpatientrecord_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmessage',
            name='clinic_patient',
            field=models.ForeignKey(blank=True, help_text='المريض المرتبط بالمحادثة (إن وُجد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clinics.clinicpatientrecord'),
        ),
    ]
