# Generated by Django 4.2.17 on 2025-10-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_chatroom_clinic_message_chatroom_clinic_patient_and_more'),
        ('clinics', '0006_clinicmessage_clinic_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpatientrecord',
            name='linked_pet',
            field=models.ForeignKey(blank=True, help_text='الحيوان المرتبط في التطبيق الرئيسي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_patient_records', to='pets.pet'),
        ),
    ]
