# Generated by Django 4.2.16 on 2025-12-06 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0007_clinicpatientrecord_linked_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('regular_price', models.DecimalField(decimal_places=2, help_text='السعر العادي (مجموع الخدمات)', max_digits=10)),
                ('package_price', models.DecimalField(decimal_places=2, help_text='سعر الباقة (مخفض)', max_digits=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, help_text='قيمة التوفير', max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باقة خدمات',
                'verbose_name_plural': 'باقات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(help_text='اسم الفئة', max_length=50)),
                ('tier_size', models.CharField(choices=[('xs', 'صغير جداً (أقل من 5 كجم)'), ('sm', 'صغير (5-10 كجم)'), ('md', 'متوسط (10-25 كجم)'), ('lg', 'كبير (25-40 كجم)'), ('xl', 'كبير جداً (أكثر من 40 كجم)')], max_length=10)),
                ('weight_range', models.CharField(blank=True, help_text='نطاق الوزن', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فئة تسعير',
                'verbose_name_plural': 'فئات التسعير',
                'ordering': ['service', 'tier_size'],
            },
        ),
        migrations.AlterModelOptions(
            name='clinicservice',
            options={'ordering': ['clinic', 'display_order', 'name'], 'verbose_name': 'خدمة طبية', 'verbose_name_plural': 'الخدمات الطبية'},
        ),
        migrations.RemoveField(
            model_name='clinicservice',
            name='price',
        ),
        migrations.AddField(
            model_name='clinicinvite',
            name='intended_pet',
            field=models.ForeignKey(blank=True, help_text='الحيوان المقصود ربطه عند قبول الدعوة (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_clinic_invites', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='applicable_pet_types',
            field=models.JSONField(default=list, help_text='أنواع الحيوانات المطبقة عليها الخدمة'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='السعر الأساسي', max_digits=10),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='has_tiered_pricing',
            field=models.BooleanField(default=False, help_text='هل لديها تسعير متدرج؟'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='خدمة مميزة'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='requires_appointment',
            field=models.BooleanField(default=True, help_text='تتطلب موعد مسبق'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='service_icon',
            field=models.CharField(blank=True, help_text='أيقونة الخدمة (emoji أو اسم)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='clinicservice',
            name='category',
            field=models.CharField(choices=[('general', 'فحص عام'), ('vaccination', 'تطعيم'), ('surgery', 'جراحة'), ('grooming', 'تنظيف وتجميل'), ('dental', 'عناية بالأسنان'), ('breeding', 'استشارات تزاوج'), ('boarding', 'إقامة ورعاية'), ('emergency', 'طوارئ'), ('diagnostic', 'فحوصات تشخيصية'), ('prescription', 'وصفات طبية'), ('other', 'خدمات أخرى')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='clinicservice',
            name='highlight',
            field=models.BooleanField(default=False, help_text='إبراز الخدمة في الواجهة (مهمل - استخدم is_featured)'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicstaff',
            unique_together={('user', 'clinic', 'role')},
        ),
        migrations.AddConstraint(
            model_name='clinicpatientrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_pet__isnull', False)), fields=('clinic', 'linked_pet'), name='uniq_clinic_linked_pet'),
        ),
        migrations.AddField(
            model_name='servicepricingtier',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='clinics.clinicservice'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(related_name='packages', to='clinics.clinicservice'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricingtier',
            unique_together={('service', 'tier_size')},
        ),
    ]
