# Generated by Django 4.2.16 on 2025-12-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_servicepackage_servicepricingtier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('food', 'طعام'), ('accessories', 'اكسسوارات'), ('medication', 'أدوية'), ('toys', 'ألعاب'), ('grooming', 'عناية'), ('other', 'أخرى')], default='other', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=80, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'منتج عيادة',
                'verbose_name_plural': 'منتجات العيادة',
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['clinic', 'is_active']),
                    models.Index(fields=['clinic', 'category']),
                ],
            },
        ),
    ]
