# Generated by Django 4.2.17 on 2026-02-20

from django.db import migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_location_point_postgis'),
        ('clinics', '0012_veterinaryappointment_clinic_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                spatial_index=True,
                srid=4326,
            ),
        ),
    ]
