# Generated by Django 4.2.17 on 2026-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_clinic_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicservice',
            name='min_duration_units',
            field=models.PositiveIntegerField(blank=True, help_text='الحد الأدنى لمدة الخدمة بوحدة التسعير (مثال: 1 يوم أو 2 ساعة)', null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='pricing_unit',
            field=models.CharField(choices=[('per_visit', 'لكل زيارة'), ('per_session', 'لكل جلسة'), ('per_hour', 'لكل ساعة'), ('per_day', 'لكل يوم'), ('per_night', 'لكل ليلة')], default='per_visit', help_text='وحدة التسعير (بالساعة/باليوم/للزيارة)', max_length=20),
        ),
        migrations.AlterField(
            model_name='veterinaryappointment',
            name='appointment_type',
            field=models.CharField(choices=[('checkup', 'فحص دوري'), ('vaccination', 'تطعيم'), ('dental', 'تنظيف أسنان'), ('follow-up', 'متابعة'), ('breeding_consultation', 'استشارة تزاوج'), ('pregnancy_check', 'فحص حمل'), ('emergency', 'طوارئ'), ('grooming', 'تنظيف وتجميل'), ('surgery', 'جراحة'), ('other', 'أخرى')], default='checkup', max_length=30),
        ),
    ]
