# Generated by Django 4.2.17 on 2026-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_clinicservice_min_duration_units_and_more'),
        ('clinics', '0014_marketplace_inquiries'),
    ]

    operations = [
    ]
