# Generated by Django 4.2.17 on 2026-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_merge_20260513_1818'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicservice',
            new_name='clinics_cli_categor_56a3a0_idx',
            old_name='clinics_cli_categor_95832a_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicservice',
            new_name='clinics_cli_is_feat_1784fa_idx',
            old_name='clinics_cli_is_feat_5d514f_idx',
        ),
    ]
