# Generated by Django 4.2.17 on 2026-10-04 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0026_providerservicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_kind', models.CharField(max_length=30)),
                ('record_id', models.CharField(max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicMedicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alert', 'تنبيه'), ('vaccine', 'تطعيم'), ('prescription', 'وصفة')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='clinicpatientdocument',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clinics.veterinarysession'),
        ),
        migrations.AddField(
            model_name='clinicpatientrecord',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinicpatientrecord',
            name='weight_recorded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicpatientdocument',
            name='category',
            field=models.CharField(choices=[('medical_record', 'سجل طبي'), ('vaccination', 'تطعيم'), ('lab_result', 'نتيجة مختبر'), ('imaging', 'تصوير طبي'), ('report', 'تقرير طبي'), ('prescription', 'وصفة طبية'), ('certificate', 'شهادة'), ('other', 'أخرى')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='clinicmedicalentry',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicmedicalentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_entries', to='clinics.clinicpatientrecord'),
        ),
        migrations.AddField(
            model_name='clinicmedicalentry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_entries', to='clinics.veterinarysession'),
        ),
        migrations.AddField(
            model_name='clinicalamendment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalamendment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicalamendment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='clinics.clinicpatientrecord'),
        ),
        migrations.AddIndex(
            model_name='clinicmedicalentry',
            index=models.Index(fields=['patient', 'kind', '-date'], name='medical_entry_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicmedicalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'prescription'), ('session__isnull', False)), fields=('session',), name='unique_session_prescription'),
        ),
    ]
