# Generated by Django 4.2.16 on 2025-08-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'سلالة',
                'verbose_name_plural': 'السلالات',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('cats', 'قطط'), ('dogs', 'كلاب'), ('birds', 'طيور'), ('other', 'أخرى')], default='cats', max_length=20)),
                ('age_months', models.PositiveIntegerField(help_text='العمر بالشهور')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='الوزن بالكيلو', max_digits=5)),
                ('description', models.TextField()),
                ('health_status', models.TextField(help_text='الحالة الصحية والتطعيمات')),
                ('is_fertile', models.BooleanField(default=True, help_text='قادر على التزاوج')),
                ('breeding_history', models.TextField(blank=True, help_text='تاريخ التزاوج السابق', null=True)),
                ('last_breeding_date', models.DateField(blank=True, help_text='تاريخ آخر تزاوج', null=True)),
                ('number_of_offspring', models.PositiveIntegerField(default=0, help_text='عدد النتاج السابق')),
                ('temperament', models.CharField(help_text='المزاج والطباع', max_length=100)),
                ('is_trained', models.BooleanField(default=False, help_text='مدرب أم لا')),
                ('good_with_kids', models.BooleanField(default=True, help_text='مناسب للأطفال')),
                ('good_with_pets', models.BooleanField(default=True, help_text='مناسب مع الحيوانات الأخرى')),
                ('main_image', models.ImageField(upload_to='pets/main/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('status', models.CharField(choices=[('available', 'متاح للتزاوج'), ('mating', 'في عملية التزاوج'), ('pregnant', 'حامل'), ('unavailable', 'غير متاح')], default='available', max_length=20)),
                ('location', models.CharField(help_text='الموقع', max_length=200)),
                ('breeding_fee', models.DecimalField(blank=True, decimal_places=2, help_text='رسوم التزاوج', max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='مجاني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حيوان أليف',
                'verbose_name_plural': 'الحيوانات الأليفة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم العيادة', max_length=200)),
                ('code', models.CharField(help_text='رمز العيادة', max_length=50, unique=True)),
                ('address', models.TextField(help_text='العنوان الكامل')),
                ('city', models.CharField(help_text='المدينة', max_length=100)),
                ('phone', models.CharField(help_text='رقم الهاتف', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='البريد الإلكتروني', max_length=254, null=True)),
                ('working_hours', models.CharField(help_text='ساعات العمل', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عيادة بيطرية',
                'verbose_name_plural': 'العيادات البيطرية',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/additional/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='رسالة من الطالب', null=True)),
                ('meeting_date', models.DateField(help_text='تاريخ المقابلة المقترح')),
                ('contact_phone', models.CharField(help_text='رقم الهاتف للتواصل', max_length=20)),
                ('agreed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_paid_by', models.CharField(choices=[('requester', 'الطالب'), ('receiver', 'المالك الآخر'), ('split', 'مناصفة')], default='requester', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('approved', 'تم الموافقة'), ('rejected', 'تم الرفض'), ('completed', 'تمت المقابلة'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text='رد المالك الآخر', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_breeding_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_breeding_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_pet', models.ForeignKey(help_text='حيوان المرسل', on_delete=django.db.models.deletion.CASCADE, related_name='sent_breeding_requests', to='pets.pet')),
                ('target_pet', models.ForeignKey(help_text='الحيوان المطلوب للمقابلة', on_delete=django.db.models.deletion.CASCADE, related_name='received_breeding_requests', to='pets.pet')),
                ('veterinary_clinic', models.ForeignKey(help_text='العيادة البيطرية للمقابلة', on_delete=django.db.models.deletion.CASCADE, to='pets.veterinaryclinic')),
            ],
            options={
                'verbose_name': 'طلب مقابلة',
                'verbose_name_plural': 'طلبات المقابلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
