# Generated by Django 4.2.16 on 2025-08-24 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('breeding_request_received', 'تم استلام طلب مقابلة جديد'), ('breeding_request_approved', 'تم قبول طلب المقابلة'), ('breeding_request_rejected', 'تم رفض طلب المقابلة'), ('breeding_request_completed', 'تم إكمال المقابلة'), ('favorite_added', 'تم إضافة حيوانك إلى المفضلة'), ('pet_status_changed', 'تم تغيير حالة حيوانك'), ('system_message', 'رسالة من النظام')], help_text='نوع الإشعار', max_length=30)),
                ('title', models.CharField(help_text='عنوان الإشعار', max_length=200)),
                ('message', models.TextField(help_text='محتوى الإشعار')),
                ('is_read', models.BooleanField(default=False, help_text='تم قراءة الإشعار')),
                ('read_at', models.DateTimeField(blank=True, help_text='تاريخ القراءة', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='بيانات إضافية للإشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_breeding_request', models.ForeignKey(blank=True, help_text='طلب المقابلة المرتبط بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.breedingrequest')),
                ('related_pet', models.ForeignKey(blank=True, help_text='الحيوان المرتبط بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(help_text='المستخدم المرسل إليه الإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pets_notifi_user_id_f9827a_idx'), models.Index(fields=['user', 'is_read'], name='pets_notifi_user_id_d7ec3b_idx')],
            },
        ),
    ]
