# Generated by Django 4.2.16 on 2025-08-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breeding_fee',
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_free',
            field=models.BooleanField(default=True, help_text='متاح للتزاوج'),
        ),
    ]
