# Generated by Django 4.2.16 on 2025-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_breeding_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='additional_certificate',
            field=models.FileField(blank=True, help_text='شهادة إضافية (PDF, JPG, PNG)', null=True, upload_to='pets/certificates/additional/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='disease_free_certificate',
            field=models.FileField(blank=True, help_text='شهادة خلو من الأمراض (PDF, JPG, PNG)', null=True, upload_to='pets/certificates/disease_free/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_certificate',
            field=models.FileField(blank=True, help_text='الشهادة الصحية البيطرية (PDF, JPG, PNG)', null=True, upload_to='pets/certificates/health/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination_certificate',
            field=models.FileField(blank=True, help_text='شهادة التطعيمات (PDF, JPG, PNG)', null=True, upload_to='pets/certificates/vaccination/'),
        ),
    ]
