# Generated by Django 4.2.16 on 2025-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_add_health_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='خط العرض', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='خط الطول', max_digits=11, null=True),
        ),
    ]
