# Generated by Django 4.2.16 on 2025-08-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_pet_latitude_pet_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='هل المحادثة نشطة')),
                ('last_message', models.TextField(blank=True, help_text='آخر رسالة', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='وقت آخر رسالة', null=True)),
                ('breeding_request', models.OneToOneField(help_text='طلب التزاوج المرتبط بالمحادثة', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='pets.breedingrequest')),
                ('last_message_sender', models.ForeignKey(blank=True, help_text='مرسل آخر رسالة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'غرفة محادثة',
                'verbose_name_plural': 'غرف المحادثة',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('system', 'رسالة نظام')], default='text', help_text='نوع الرسالة', max_length=10)),
                ('content', models.TextField(help_text='محتوى الرسالة')),
                ('attachment', models.FileField(blank=True, help_text='مرفق (صورة أو ملف)', null=True, upload_to='chat/attachments/')),
                ('is_read', models.BooleanField(default=False, help_text='هل تم قراءة الرسالة')),
                ('read_at', models.DateTimeField(blank=True, help_text='وقت القراءة', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(help_text='غرفة المحادثة', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pets.chatroom')),
                ('sender', models.ForeignKey(help_text='مرسل الرسالة', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
    ]
