# Generated by Django 4.2.16 on 2025-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_add_chat_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_sender',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='firebase_chat_id',
            field=models.CharField(default='', help_text='معرف المحادثة في Firebase', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
