# Generated by Django 4.2.16 on 2025-08-24 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0007_migrate_to_firebase_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'متاح للتزاوج'), ('mating', 'في عملية التزاوج'), ('pregnant', 'حامل'), ('unavailable', 'غير متاح'), ('available_for_adoption', 'متاح للتبني'), ('adoption_pending', 'التبني قيد المراجعة'), ('adopted', 'تم تبنيه')], default='available', max_length=30),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('adopter_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('adopter_address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('adopter_id_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('living_situation', models.CharField(choices=[('apartment', 'شقة'), ('house_small', 'منزل صغير'), ('house_large', 'منزل كبير'), ('farm', 'مزرعة')], max_length=20, verbose_name='حالة السكن')),
                ('has_yard', models.BooleanField(default=False, verbose_name='يوجد فناء')),
                ('yard_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='حجم الفناء')),
                ('other_pets', models.TextField(blank=True, null=True, verbose_name='حيوانات أخرى في المنزل')),
                ('previous_pet_experience', models.TextField(verbose_name='الخبرة السابقة مع الحيوانات')),
                ('reason_for_adoption', models.TextField(verbose_name='سبب الرغبة في التبني')),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الميزانية الشهرية للحيوان')),
                ('has_vet_nearby', models.BooleanField(default=False, verbose_name='يوجد طبيب بيطري قريب')),
                ('family_size', models.PositiveIntegerField(verbose_name='عدد أفراد العائلة')),
                ('has_children', models.BooleanField(default=False, verbose_name='يوجد أطفال')),
                ('children_ages', models.CharField(blank=True, max_length=50, null=True, verbose_name='أعمار الأطفال')),
                ('agrees_to_terms', models.BooleanField(default=False, verbose_name='موافق على الشروط')),
                ('agrees_to_visit', models.BooleanField(default=False, verbose_name='موافق على زيارة المنزل')),
                ('agrees_to_return', models.BooleanField(default=False, verbose_name='موافق على إعادة الحيوان إذا لزم الأمر')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المالك')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب التبني')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet', verbose_name='الحيوان المطلوب تبنيه')),
            ],
            options={
                'verbose_name': 'طلب تبني',
                'verbose_name_plural': 'طلبات التبني',
                'ordering': ['-created_at'],
                'unique_together': {('adopter', 'pet', 'status')},
            },
        ),
    ]
