# Generated by Django 4.2.16 on 2025-08-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_status_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_chat_room',
            field=models.ForeignKey(blank=True, help_text='المحادثة المرتبطة بالإشعار', null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.chatroom'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breeding_request_received', 'تم استلام طلب مقابلة جديد'), ('breeding_request_approved', 'تم قبول طلب المقابلة'), ('breeding_request_rejected', 'تم رفض طلب المقابلة'), ('breeding_request_completed', 'تم إكمال المقابلة'), ('favorite_added', 'تم إضافة حيوانك إلى المفضلة'), ('pet_status_changed', 'تم تغيير حالة حيوانك'), ('system_message', 'رسالة من النظام'), ('chat_message_received', 'تم استلام رسالة جديدة')], help_text='نوع الإشعار', max_length=30),
        ),
    ]
