# Generated by Django 4.2.16 on 2025-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_notification_related_chat_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='pet_type',
            field=models.CharField(choices=[('cats', 'قطط'), ('dogs', 'كلاب'), ('birds', 'طيور'), ('fish', 'أسماك')], default='cats', help_text='نوع الحيوان الذي تنتمي إليه هذه السلالة', max_length=20),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('name', 'pet_type')},
        ),
    ]
