# Generated by Django 4.2.16 on 2025-08-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_breed_pet_type_alter_breed_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='adopter_full_name',
            new_name='adopter_name',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='agrees_to_return',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='agrees_to_terms',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='agrees_to_visit',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='children_ages',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='has_vet_nearby',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='has_yard',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='living_situation',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='other_pets',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='previous_pet_experience',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='yard_size',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_age',
            field=models.PositiveIntegerField(default=5, verbose_name='العمر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_email',
            field=models.EmailField(default='', max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_occupation',
            field=models.CharField(default='', max_length=100, verbose_name='المهنة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='agrees_to_follow_up',
            field=models.BooleanField(default=True, verbose_name='موافقة على المتابعة'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='agrees_to_training',
            field=models.BooleanField(default=True, verbose_name='موافقة على التدريب'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='agrees_to_vet_care',
            field=models.BooleanField(default=True, verbose_name='موافقة على الرعاية البيطرية'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='emergency_plan',
            field=models.TextField(default='سيتم التعامل مع الطوارئ فوراً', verbose_name='خطة الطوارئ'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='exercise_plan',
            field=models.TextField(default='ستتم ممارسة التمارين يومياً', verbose_name='خطة التمارين'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='experience_level',
            field=models.CharField(default='basic', max_length=50, verbose_name='مستوى الخبرة'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='family_agreement',
            field=models.BooleanField(default=True, verbose_name='موافقة العائلة'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='family_members',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد أفراد العائلة'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='feeding_plan',
            field=models.TextField(default='ستتم العناية بالتغذية بانتظام', verbose_name='خطة التغذية'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='housing_type',
            field=models.CharField(default='apartment', max_length=50, verbose_name='نوع السكن'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='time_availability',
            field=models.CharField(default='high', max_length=50, verbose_name='الوقت المتاح'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='vet_care_plan',
            field=models.TextField(default='ستتم المتابعة البيطرية المنتظمة', verbose_name='خطة الرعاية البيطرية'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='reason_for_adoption',
            field=models.TextField(default='الرغبة في تربية حيوان أليف', verbose_name='سبب التبني'),
        ),
    ]
