# Generated by Django 4.2.16 on 2025-08-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_rename_adopter_full_name_adoptionrequest_adopter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='adoption_request',
            field=models.OneToOneField(blank=True, help_text='طلب التبني المرتبط بالمحادثة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='pets.adoptionrequest'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='breeding_request',
            field=models.OneToOneField(blank=True, help_text='طلب التزاوج المرتبط بالمحادثة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='pets.breedingrequest'),
        ),
    ]
