# Generated by Django 4.2.16 on 2025-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_chatroom_adoption_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hosting_preference',
            field=models.CharField(choices=[('my_place', 'عندي (في منزلي/حديقتي)'), ('other_place', 'عند صاحب الحيوان الآخر'), ('both', 'كلاهما مناسب'), ('flexible', 'مرن')], default='flexible', help_text='تفضيل الأليف', max_length=20),
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet_type',
            field=models.CharField(choices=[('cats', 'قطط'), ('dogs', 'كلاب')], default='cats', help_text='نوع الحيوان الذي تنتمي إليه هذه السلالة', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('cats', 'قطط'), ('dogs', 'كلاب')], default='cats', max_length=20),
        ),
    ]
