# Generated by Django 4.2.16 on 2025-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_pet_hosting_preference_alter_breed_pet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='adopter_id_number',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول'),
        ),
    ]
