# Generated by Django 4.2.16 on 2025-08-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_add_adopter_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrequest',
            name='veterinary_clinic',
            field=models.ForeignKey(blank=True, help_text='العيادة البيطرية للمقابلة (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.veterinaryclinic'),
        ),
    ]
