# Generated by Django 4.2.16 on 2025-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_make_veterinary_clinic_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_fertile',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='temperament',
        ),
        migrations.AddField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='رسوم التبني', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='breeding_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='رسوم التزاوج', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_free_breeding',
            field=models.BooleanField(default=True, help_text='هل التزاوج مجاني؟'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_free',
            field=models.BooleanField(default=True, help_text='هل التبني مجاني؟'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(help_text='الموقع (المدينة/الحي)', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
