# Generated by Django 4.2.16 on 2025-09-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_remove_deleted_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adoption_fee',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breeding_fee',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_free_breeding',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
    ]
