# Generated by Django 4.2.17 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_remove_weight_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breeding_request_received', 'تم استلام طلب مقابلة جديد'), ('breeding_request_approved', 'تم قبول طلب المقابلة'), ('breeding_request_rejected', 'تم رفض طلب المقابلة'), ('breeding_request_completed', 'تم إكمال المقابلة'), ('favorite_added', 'تم إضافة حيوانك إلى المفضلة'), ('pet_status_changed', 'تم تغيير حالة حيوانك'), ('system_message', 'رسالة من النظام'), ('chat_message_received', 'تم استلام رسالة جديدة'), ('pet_nearby', 'حيوان جديد بالقرب منك')], help_text='نوع الإشعار', max_length=30),
        ),
    ]
