# Generated by Django 4.2.17 on 2025-10-10 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0006_clinicmessage_clinic_patient'),
        ('pets', '0019_make_meeting_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='clinic_message',
            field=models.OneToOneField(blank=True, help_text='رسالة العيادة المرتبطة بالمحادثة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='clinics.clinicmessage'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='clinic_patient',
            field=models.ForeignKey(blank=True, help_text='مريض العيادة المرتبط بالمحادثة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='clinics.clinicpatientrecord'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='clinic_staff',
            field=models.ForeignKey(blank=True, help_text='عضو العيادة الذي أنشأ المحادثة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breeding_request_received', 'تم استلام طلب مقابلة جديد'), ('breeding_request_approved', 'تم قبول طلب المقابلة'), ('breeding_request_rejected', 'تم رفض طلب المقابلة'), ('breeding_request_completed', 'تم إكمال المقابلة'), ('favorite_added', 'تم إضافة حيوانك إلى المفضلة'), ('pet_status_changed', 'تم تغيير حالة حيوانك'), ('system_message', 'رسالة من النظام'), ('chat_message_received', 'تم استلام رسالة جديدة'), ('pet_nearby', 'حيوان جديد بالقرب منك'), ('clinic_broadcast', 'إشعار من العيادة'), ('clinic_invite', 'دعوة ربط عيادة')], help_text='نوع الإشعار', max_length=30),
        ),
    ]
