# Generated by Django 4.2.17 on 2025-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_expand_notification_type_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='emergency_plan',
            field=models.TextField(blank=True, help_text='كيفية التعامل مع الحالات الطارئة (اختياري)', null=True, verbose_name='خطة الطوارئ'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='exercise_plan',
            field=models.TextField(blank=True, help_text='خطة التمارين اليومية أو الأسبوعية (اختياري)', null=True, verbose_name='خطة التمارين'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='feeding_plan',
            field=models.TextField(blank=True, help_text='خطة العناية بالتغذية (اختياري)', null=True, verbose_name='خطة التغذية'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='vet_care_plan',
            field=models.TextField(blank=True, help_text='خطة الزيارات البيطرية والمتابعة الصحية (اختياري)', null=True, verbose_name='خطة الرعاية البيطرية'),
        ),
    ]
