# Generated by Django 4.2.16 on 2025-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_alter_adoptionrequest_emergency_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breeding_request_received', 'تم استلام طلب مقابلة جديد'), ('breeding_request_approved', 'تم قبول طلب المقابلة'), ('breeding_request_rejected', 'تم رفض طلب المقابلة'), ('breeding_request_completed', 'تم إكمال المقابلة'), ('favorite_added', 'تم إضافة حيوانك إلى المفضلة'), ('pet_status_changed', 'تم تغيير حالة حيوانك'), ('system_message', 'رسالة من النظام'), ('chat_message_received', 'تم استلام رسالة جديدة'), ('pet_nearby', 'حيوان جديد بالقرب منك'), ('adoption_pet_nearby', 'حيوان للتبني بالقرب منك'), ('clinic_broadcast', 'إشعار من العيادة'), ('clinic_invite', 'دعوة ربط عيادة'), ('breeding_request_pending_reminder', 'تذكير بطلب مقابلة معلق'), ('adoption_request_received', 'تم استلام طلب تبني جديد'), ('adoption_request_approved', 'تم قبول طلب التبني'), ('adoption_request_pending_reminder', 'تذكير بطلب تبني معلق')], help_text='نوع الإشعار', max_length=64),
        ),
    ]
