# Generated by Django 4.2.17 on 2026-02-20 23:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
