# Generated by Django 4.2.17 on 2026-02-20

from django.contrib.gis.geos import Point
from django.db import migrations


def _build_point(latitude, longitude):
    if latitude is None or longitude is None:
        return None
    try:
        lat = float(latitude)
        lng = float(longitude)
    except (TypeError, ValueError):
        return None
    if lat < -90 or lat > 90 or lng < -180 or lng > 180:
        return None
    return Point(lng, lat, srid=4326)


def backfill_location_points(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Pet = apps.get_model('pets', 'Pet')
    Clinic = apps.get_model('clinics', 'Clinic')

    for user in User.objects.filter(latitude__isnull=False, longitude__isnull=False):
        point = _build_point(user.latitude, user.longitude)
        if point:
            user.location_point = point
            user.save(update_fields=['location_point'])

    for clinic in Clinic.objects.filter(latitude__isnull=False, longitude__isnull=False):
        point = _build_point(clinic.latitude, clinic.longitude)
        if point:
            clinic.location_point = point
            clinic.save(update_fields=['location_point'])

    for pet in Pet.objects.select_related('owner').all():
        point = _build_point(pet.latitude, pet.longitude)
        if point is None and pet.owner_id:
            point = _build_point(getattr(pet.owner, 'latitude', None), getattr(pet.owner, 'longitude', None))
        if point:
            pet.location_point = point
            pet.save(update_fields=['location_point'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_location_point_postgis'),
        ('clinics', '0013_clinic_location_point'),
        ('pets', '0024_pet_location_point'),
    ]

    operations = [
        migrations.RunPython(backfill_location_points, migrations.RunPython.noop),
    ]
