# Generated by Codex on 2026-07-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0033_savedsearch_savedsearchmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='pending'),
                fields=('adopter', 'pet'),
                name='pets_adoption_pending_unique',
            ),
        ),
    ]
