# Generated by Django 4.2.17 on 2026-09-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0036_notification_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='availability_check_due_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='availability_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='availability_prompt_after',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='discovery_paused_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breeding_request_received', 'New breeding request received'), ('breeding_request_approved', 'Breeding request approved'), ('breeding_request_rejected', 'Breeding request rejected'), ('breeding_request_completed', 'Breeding meeting completed'), ('favorite_added', 'Pet added to favorites'), ('pet_availability_check', 'Pet availability check'), ('pet_status_changed', 'Pet status changed'), ('system_message', 'System message'), ('chat_message_received', 'New message received'), ('pet_nearby', 'A new pet is nearby'), ('adoption_pet_nearby', 'An adoptable pet is nearby'), ('saved_search_match', 'New saved-search match'), ('clinic_broadcast', 'Clinic notification'), ('clinic_invite', 'Clinic connection invitation'), ('breeding_request_pending_reminder', 'Pending breeding request reminder'), ('adoption_request_received', 'New adoption request received'), ('adoption_request_approved', 'Adoption request approved'), ('adoption_request_pending_reminder', 'Pending adoption request reminder'), ('account_verification_approved', 'Account verification approved')], help_text='نوع الإشعار', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='event_type',
            field=models.CharField(choices=[('pet_availability_push', 'Pet availability push'), ('pet_created', 'Pet created'), ('breeding_request_received', 'Breeding request received'), ('breeding_request_approved', 'Breeding request approved'), ('breeding_request_rejected', 'Breeding request rejected'), ('adoption_request_received', 'Adoption request received'), ('adoption_request_approved', 'Adoption request approved'), ('chat_message_received', 'Chat message received'), ('clinic_invite_push', 'Clinic invite push'), ('clinic_broadcast_push', 'Clinic broadcast push'), ('clinic_chat_message_push', 'Clinic chat message push'), ('clinic_booking_push', 'Clinic booking push'), ('account_verification_approved_push', 'Account verification approved push')], max_length=64),
        ),
        migrations.CreateModel(
            name='PetAvailabilityFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_kind', models.CharField(choices=[('adoption', 'Adoption'), ('breeding', 'Breeding')], max_length=10)),
                ('request_id', models.PositiveBigIntegerField()),
                ('approved_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_followups', to='pets.pet')),
            ],
            options={
                'indexes': [models.Index(fields=['pet', 'resolved_at'], name='pet_availability_open_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='petavailabilityfollowup',
            constraint=models.UniqueConstraint(fields=('pet', 'request_kind', 'request_id'), name='pet_availability_request_unique'),
        ),
    ]
